name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Check out code
        uses: actions/checkout@v4

      - name: Unit test
        run: go test -cover ./...
